use_frameworks!

target 'iOS Example' do
    platform :ios, '12.0'
    pod 'Swash', :path => '../'
end

target 'tvOS Example' do
    platform :tvos, '12.0'
    pod 'Swash', :path => '../'
end

target 'watchOS Example Extension' do
    platform :watchos, '5.0'
    pod 'Swash', :path => '../'
end

target 'iOS Tests' do
    platform :ios, '12.0'
    pod 'Swash', :path => '../'
end

target 'tvOS Tests' do
    platform :tvos, '12.0'
    pod 'Swash', :path => '../'
end
