use_frameworks!

target 'Swash_Example' do
    platform :ios, '12.0'
    pod 'Swash', :path => '../'
end

target 'Swash_Tests' do
    platform :ios, '12.0'
    pod 'Swash', :path => '../'
end

target 'Swash_tvOS_Example' do
    platform :tvos, '12.0'
    pod 'Swash', :path => '../'
end
